[project]
name = "collabsync-backend"
version = "0.1.0"
description = "Multi-threaded collaborative editor backend"
requires-python = ">=3.10"
dependencies = [
    "websockets>=12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


